#
#        » Leaked by @FichaDev «
#        Studio: t.me/FichaDev
#        Hentai: t.me/FichaHentai
#
group_messages:
  griefer: '&#FB7777▶ &7Для получения доступа к данной команде требуеться привилегия &#FB7777&l«ɢʀɪᴇғᴇʀ»&7, о которой можно узнать в меню &b/priv'
  mustang: '&#EEBE00▶ &7Для получения доступа к данной команде требуеться привилегия &#EEBE00&l«ᴍᴜsᴛᴀɴɢ»&7, о которой можно узнать в меню &b/priv'
  ghast: '&#2AFBFF▶ &7Для получения доступа к данной команде требуеться привилегия &#2AFBFF&l«ɢʜᴀsᴛ»&7, о которой можно узнать в меню &b/priv'
  wither: '&#FB4F00▶ &7Для получения доступа к данной команде требуеться привилегия &#FB4F00&l«ᴡɪᴛʜᴇʀ»&7, о которой можно узнать в меню &b/priv'
  kraken: '&#2DFD00▶ &7Для получения доступа к данной команде требуеться привилегия &#2DFD00&l«ᴋ&r&#24FD1E&lʀ&r&#1BFD3D&lᴀ&r&#12FD5B&lᴋ&r&#09FD7A&lᴇ&r&#00FD98&lɴ»&7, о которой можно узнать в меню &b/priv'
  dragon: '&#E000FF▶ &7Для получения доступа к данной команде требуеться привилегия &#E000FF&l«ᴅ&r&#D80CFF&lʀ&r&#D019FF&lᴀ&r&#C925FF&lɢ&r&#C132FF&lᴏ&r&#B93EFF&lɴ»&7, о которой можно узнать в меню &b/priv'
  stinger: '&#FF0000▶ &7Для получения доступа к данной команде требуеться привилегия &#FF0000&l«s&r&#FF0E00&lᴛ&r&#FF1B00&lɪ&r&#FF2900&lɴ&r&#FF3600&lɢ&r&#FF4400&lᴇ&r&#FF5100&lʀ»&7, о которой можно узнать в меню &b/priv'
  eternity: '&#FF0095▶ &7Для получения доступа к данной команде требуеться привилегия &#FF0095&l«ᴇ&r&#FF00A2&lᴛ&r&#FF00AF&lᴇ&r&#FF00BC&lʀ&r&#FF00CA&lɴ&r&#FF00D7&lɪ&r&#FF00E4&lᴛ&r&#FF00F1&lʏ»&7, о которой можно узнать в меню &b/priv'